sudo: required

language: php
php:
  - '7.1'
  - '7.2'

services:
  - docker

install:
  - make travis install

before_script:
  - sudo /etc/init.d/mysql stop
  - cp .env.travis .env

script:
  - make no-docker test
