sudo: required

language: php
php:
  - '7.1'
  - '7.2'

services:
  - docker

variables:
  DOCKER_DRIVER: overlay2
  COMPOSE_FILE: "docker-compose.yml:docker-compose.travis-ci.yml"

before_install:
  - make install