sudo: required

language: php

php:
  - '7.1'
  - '7.2'

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

services:
  - docker

before_install:
  - sudo /etc/init.d/mysql stop

install:
  - make travis install

script:
  - make no-docker test
