sudo: required

language: php
php:
  - '7.1'
  - '7.2'

env:
  APP_ENV=dev
  APP_SECRET=eb7ac76ae3a8d523e374902b88f622dc
  DATABASE_URL=mysql://root:@database:3306/db_name

services:
  - docker

install:
  - make travis install

script:
  - make no-docker test
