version: '3.2'

services:
  database:
    image: mariadb:10.3
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

  http:
    image: nginx:1-alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/srv/public/:ro

  php:
    build:
      context: ./docker/php
    working_dir: /srv
    volumes:
      - ./:/srv/:cached
      - ./var/cache:/srv/var/cache
      - ./var/log:/srv/var/log

  node:
    build:
      context: ./docker/node
    working_dir: /srv
    volumes:
      - ./:/srv/

volumes:
  database: ~
