version: '3.2'

services:
  database:
    image: mariadb:10.3
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

  node:
    build:
      context: ./docker/node
    working_dir: /srv
    volumes:
      - ./:/srv/

volumes:
  database: ~
